# Generated by Django 3.2.13 on 2023-09-19 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hobbies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('practice_duration', models.CharField(max_length=70)),
                ('frequency', models.CharField(choices=[('N', 'Never'), ('S', 'Sometimes'), ('A', 'Always')], default='', max_length=1)),
                ('benefits', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Learn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('category', models.CharField(choices=[('F', 'Fun'), ('W', 'Work'), ('H', 'Health')], default='', max_length=1)),
                ('priority', models.IntegerField()),
                ('current_level', models.CharField(max_length=70)),
            ],
        ),
    ]
